### ISSUE TITLE
Small documentation nit

### ISSUE THREAD

**Issue by itamarst** [drhagen/tabeline#3]
Hi, this looks cool! One small suggestion: switch "he" in docs to "they", presumably not all your users will be male.

**Comment by drhagen** [comment]
The docs are written in General American English. In my native dialect, "he" is gender-neutral when there is no specific person being referenced. I should probably make an effort to write in "Hollywood English", given its dominance on the world stage, but it takes extra effort to maintain text in a non-native dialect. Realistically, it will not be high on my priority list to try.

**Comment by drhagen** [comment]
There actually was not very much of this, so I just pluralized everything. Pronoun usage now conforms to both General American and Hollywood English. Future documentation PRs will be required to maintain this standard.
